export type FailureCode =
  | 'INSUFFICIENT_STOCK'
  | 'PRODUCT_NOT_FOUND'
  | 'RETRIES_EXHAUSTED'
  | 'MALFORMED_EVENT'
  | 'ORDER_NOT_FOUND'
  | 'ORDER_NOT_REPROCESSABLE'
  | 'INVALID_STATE_TRANSITION'
  | 'VALIDATION_ERROR'
  | 'DUPLICATE_PRODUCT_IN_ORDER';
